### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Jamesking56** [mattwells/faker-vehicle#3]
@mattwells Is this abandoned? If so, I'd like to make my own version of your package with a few additions. Please reply back and let me know so we can sort this out.

We can then mark this as an abandoned composer dependency and suggest my new package when people run `composer install`. This way your existing users will be notified of this in their projects.

**Comment by mattwells** [comment]
I wouldn't say it was abandoned as I still use it, I have just had no need to modify it. I'm happy for you to do your own thing though :)

**Comment by Jamesking56** [comment]
Thanks for replying so quickly, I'll be working on a new library for my projects which will incorporate both UK and US vehicles (including private registrations) published on packagist. Will reply here with a packagist link when ready :)

**Comment by mattwells** [comment]
@Jamesking56 I thought you might be interested to know that I have added support for US license plates

**Comment by Jamesking56** [comment]
Cool :+1:
